version: 2.1

jobs:
  build-image:
    parameters:
      module:
        description: module to build
        type: string
      build_platform:
        description: build_platform - arm / amd
        type: string
    environment:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_REPOSITORY: arm64-compat
      ZULU_JDK_VERSION: 11.0.15-1
    machine:
      image: ubuntu-2004:202101-01
    resource_class: << parameters.build_platform >>
    steps:
    - checkout
    - run:
        name: Checkout Submodule
        command: git submodule update --init -- << parameters.module >>
    - restore_cache:
        key: m2-{{ checksum "<< parameters.module >>/pom.xml" }}
    - run:
        name: Install tox for testing
        command: pip install tox
    - run:
        name: Build
        command: ./build-images.sh << parameters.module >>
    - save_cache:
        key: m2-{{ checksum "<< parameters.module >>/pom.xml" }}
        paths:
        - ~/.m2
    - run:
        name: Docker Login
        command: echo $GITHUB_TOKEN | docker login -u $GITHUB_USERNAME --password-stdin $DOCKER_REGISTRY
    - run:
        name: Deploy
        command: ./push-images.sh << parameters.module >>

workflows:
  workflow:
    jobs:
    - build-image:
        name: build-<< matrix.module >>-<< matrix.build_platform >>
        matrix:
          parameters:
            module:
            - common-docker
            build_platform:
            - arm.medium
            - medium
    - build-image:
        name: build-<< matrix.module >>-<< matrix.build_platform >>
        matrix:
          parameters:
            module:
            - schema-registry-images
            - kafka-images
            - kafka-rest-images
            - control-center-images
            - ksql-images
            build_platform:
            - arm.medium
            - medium
        requires:
        - build-common-docker-<< matrix.build_platform >>
    - build-image:
        name: build-<<matrix.module >>-<< matrix.build_platform >>
        matrix:
          parameters:
            module:
            - kafka-replicator-images
            build_platform:
            - arm.medium
            - medium
        requires:
        - build-kafka-images-<< matrix.build_platform >>
